### PR TITLE
Enable reuse license checks

### PR DESCRIPTION
**Pull request by ray-milkey**

### CODE REVIEW

**Comment by ray-milkey** [comment]
retest this please

**Comment by ray-milkey** [comment]
retest this please

**Comment by ray-milkey** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Comment by ray-milkey** [comment]
retest this please

**Comment by ray-milkey** [comment]
retest this please

**Review by SeanCondon — APPROVED** [review]

**Pull request merged**
