### PR TITLE
Partial unit tests of settings components.

### PR DESCRIPTION
**Pull request by karthik-zensark**

### CODE REVIEW

**Comment by SeanCondon** [comment]
retest this please

**Comment by karthik-zensark** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
retest this please

**Review by SeanCondon — APPROVED** [review]

**Pull request merged**
